version: '3.8'
services:
  db:
    container_name: test
    restart: unless-stopped
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mydb'
    ports:
      - 3308:3308
    volumes:
      - ./mysql-data:/var/lib/mysql